install:
  - choco install gitversion.portable -pre -y
  - choco install gitlink -y

configuration: 
  - Release
  - Debug

build_script:
  - cmd: nuget restore NDesk.Options.Fork\NDesk.Options.Fork.sln
  - cmd: gitversion /l console /output buildserver /updateAssemblyInfo
  
  - cmd: msbuild NDesk.Options.Fork\NDesk.Options.Fork.sln
  
  - cmd: ECHO GitLink NDesk.Options.Fork\ -u https://github.com/torston/ndesk.options.fork -c %CONFIGURATION%
  - cmd: GitLink . -u https://github.com/torston/ndesk.options.fork -c %CONFIGURATION%
  
  - cmd: ECHO nuget pack nuget\NDesk.Options.Fork.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: nuget pack nuget\NDesk.Options.Fork.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: appveyor PushArtifact if ["%CONFIGURATION%"] == ["Release"] "NDesk.Options.Fork.%GitVersion_NuGetVersion%.nupkg"
  - cmd: appveyor PushArtifact "NDesk.Options.Fork\bin\Release\NDesk.Options.Fork.dll"
  - cmd: appveyor PushArtifact if ["%CONFIGURATION%"] == ["Debug"]"NDesk.Options.Fork\bin\Release\NDesk.Options.Fork.pdb"
