install:
  - choco install gitversion.portable -pre -y
  - choco install gitlink -y

configuration: Release

build_script:
  - cmd: nuget restore Ndesk.Options.Fork\Ndesk.Options.Fork.sln
  - cmd: gitversion /l console /output buildserver /updateAssemblyInfo
  
  - cmd: msbuild Ndesk.Options.Fork\Ndesk.Options.Fork.sln
  
  - cmd: ECHO GitLink Ndesk.Options.Fork\ -u https://github.com/torston/ndesk.options.fork -c %CONFIGURATION%
  - cmd: GitLink . -u https://github.com/torston/ndesk.options.fork -c %CONFIGURATION%
  
  - cmd: ECHO nuget pack nuget\Ndesk.Options.Fork.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: nuget pack nuget\Ndesk.Options.Fork.nuspec -version "%GitVersion_NuGetVersion%" -prop "configuration=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Ndesk.Options.Fork.%GitVersion_NuGetVersion%.nupkg"